version: '3'
services:
  front:    
    build: ./front
    ports:
      - "5173:5173"
    image: "front-vue:v0.1"
    tty: true
    restart: always
    volumes:
      - ./front:/app
    command: sh entrypoint.sh
    networks:
      - red2

  db:
    image: postgres:16-alpine
    env_file:
      - ../config/config.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - red2

  server:    
    build: ./server
    env_file:
      - ../config/config.env
    ports:
      - "8080:8080"
    image: "server:v0.1"
    tty: true
    volumes:
      - ./server:/usr/src/app
    restart: always
    command: sh entrypoint.sh
    depends_on:
      - db
    networks:
      - red2
volumes:
  postgres_data:
networks:
  red2:
    driver: bridge
